version: '3'
services:
  cidades:
    image: calend_estados  # Nome da sua imagem já criada
    build:
      context: .          # Diretório do Dockerfile
    environment:
      SLACK_TOKEN: ${SLACK_TOKEN}           # Variáveis de ambiente serão enviadas via Terraform
      SLACK_CHANNEL: ${SLACK_CHANNEL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
